export const STUDENTSFETCH = 'STUDENTSFETCH';
export const ASSIGNMENTSFETCH = 'ASSIGNMENTSFETCH';
export const STUDENTUPDATE = 'STUDENTUPDATE';
export const ASSIGNMENTUPDATE = 'ASSIGNMENTUPDATE';
export const ASSIGNMENTADD = 'ASSIGNMENTADD';
export const STUDENTADD = 'STUDENTADD';
export const STUDENTDELETE = 'STUDENTDELETE';
export const ASSIGNMENTDELETE = 'ASSIGNMENTDELETE';
