export const STUDENTSELECT = 'STUDENTSELECT';
export const ASSIGNMENTSELECT = 'ASSIGNMENTSELECT';
export const MENUITEMSELECT = 'MENUITEMSELECT';
export const STICKYSELECT = 'STICKYSELECT';
export const THEMESELECT = 'THEMESELECT';
export const BACKGROUNDSELECT = 'BACKGROUNDSELECT';